name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install coin-or cbc solver
      run: sudo apt-get install -y coinor-libcbc-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
